spinlock & rwlock
condy0919/dpdk-rs pull request #7
Opened 2019-07-06 09:31 UTC by condy0919

2019-07-06 13:35 UTC, iovxw requested changes

2019-07-06 13:35 UTC, iovxw commented on src/core/rwlock.rs
> +            panic!("rwlock still locked");
应当添加[检查](https://doc.rust-lang.org/std/thread/fn.panicking.html)以避免 `thread panicked while panicking`

2019-07-06 13:35 UTC, iovxw commented on src/core/mod.rs
> +    static CURRENT_TID: RefCell<i32> = RefCell::new(-1);
对于 `Copy` 的类型应直接使用 `Cell`

2019-07-06 13:35 UTC, iovxw commented on src/core/rwlock.rs
> +    fn get_cnt_mut(&self) -> &mut AtomicI32 {
应标记为 `unsafe`，或者干脆别写这函数

2019-07-06 13:35 UTC, iovxw commented on src/core/rwlock.rs
> +    pub fn write_unlock(&self) {
RAII

2019-07-06 13:35 UTC, iovxw commented on src/core/spinlock.rs
> +    pub fn trylock(&self) -> bool {
`_`

2019-07-07 14:56 UTC, condy0919 commented on src/core/spinlock.rs
> +    pub fn trylock(&self) -> bool {
拒绝

2019-07-07 14:56 UTC, condy0919 commented on src/core/rwlock.rs
> +    pub fn write_unlock(&self) {
暂时不需要

2019-07-07 14:56 UTC, merged